# Generated by Django 5.2.3 on 2025-07-01 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_products', to='fridges.fridge'),
        ),
    ]
