# Generated by Django 5.2.3 on 2025-07-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0002_alter_fridgeproduct_fridge'),
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fridgeproduct',
            unique_together={('fridge', 'product')},
        ),
    ]
