# Generated by Django 5.2.3 on 2025-07-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteRecipe',
        ),
    ]
