# Generated by Django 5.2.3 on 2025-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
