# Generated by Django 5.2.3 on 2025-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_path',
            new_name='image',
        ),
    ]
