# Generated by Django 5.2.3 on 2025-07-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('recipes', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'product')},
        ),
    ]
